arch = "nice_eeg"
data_path = "/kreka/research/willy/side/brain_datasets/alljoined-isolated-epochs-2025-12-25/alljoined-isolated-epochs-2025-12-25-train.safetensors"
dataset = "sparse_classification"
class_col = "super_category_id"

epochs = 100
shuffle=false

[nice_eeg]
spatial = "channel"
emb_size = 40
num_classes = 8
dropout_rate = 0
sequence_len=78
num_channels=32