arch = "nice_eeg"
data_path = "/kreka/research/willy/side/brain_datasets/alljoined-isolated-epochs-2025-12-25/alljoined-isolated-epochs-2025-12-25-train.safetensors"
dataset = "sparse_classification"
class_col = "subject"

[nice_eeg]
spatial = "ga"  # or "sa" for self-attention
emb_size = 40
num_classes = 20
dropout_rate = 0.3
sequence_len=78
num_channels=32