arch = "eegnet"
data_path = "/kreka/research/willy/side/brain_datasets/things/things-processed-fixed-v2-2025-12-26/things-processed-fixed-v2-2025-12-26.safetensors"
dataset = "things_eeg_classification"
class_col = "objectnumber"

epochs = 100

[eegnet]
num_channels = 63
num_samples = 151
num_classes = 1854
F1=64
F2=128
D=16