arch = "classifier"
data_path = "/kreka/research/willy/side/brain_datasets/things/things-sub-01-only-2025-12-27/things-sub-01-only-2025-12-27.safetensors"
dataset = "things_eeg_classification"
class_col = "objectnumber"

epochs = 100
batch_size=1024

[classifier]
encoder_dim=1024
heads=8
sequence_len = 63
max_tokens = 256
num_classes = 1854
tokenizer_method = "eegnet"
classifier_method="mlp"