[project]
name = "brain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "datasets>=4.4.1",
    "ipykernel>=7.1.0",
    "mne>=1.11.0",
    "polars>=1.36.1",
    "streamlit>=1.52.1",
    "torch>=2.9.1",
]
