data_path = "/kreka/research/willy/side/brain_datasets/alljoined-window-2025-12-14/alljoined-window-2025-12-14-train.safetensors"
dataset = "sparse"

epochs = 10
batch_size=128

[mae]
encoder_dim = 4096
decoder_dim = 2048
masking_ratio = 0.75
depth = 6
heads = 16
dim_head = 64
mask_on = "channels"
max_tokens=32
sequence_len=256
