arch = "classifier"
data_path = "/kreka/research/willy/side/brain_datasets/alljoined-preprocessed-combined-2025-12-22"
dataset = "aj_preprocessed_classification"
class_col = "category_num"

epochs = 10

[classifier]
encoder_dim = 1024
heads = 8
sequence_len = 32
max_tokens = 308
num_classes = 1654