arch = "classifier"
data_path = "/kreka/research/willy/side/brain_datasets/alljoined-epochs-2025-12-21/alljoined-epochs-2025-12-21-train.safetensors"
dataset = "sparse_classification"
class_col = "category_num"

epochs = 10

[classifier]
encoder_dim = 1024
heads = 8
sequence_len = 32
max_tokens = 308
num_classes = 1654