arch = "eegnet"
data_path = "/kreka/research/willy/side/brain_datasets/alljoined-preprocessed-combined-2025-12-22"
dataset = "aj_preprocessed_classification"
class_col = "super_category_id"

epochs = 10

[eegnet]
num_channels = 32
num_samples = 250
num_classes = 8
