data_path = "/kreka/research/willy/side/brain_datasets/alljoined-window-2025-12-14/alljoined-window-2025-12-14-train.safetensors"
dataset = "sparse"

epochs=100

[vit]
sample_len=256
patch_len=16
num_classes=1000
dim=4096
depth=12
heads=64
mlp_dim=2048
dropout=0.1
emb_dropout=0.1
channels=32

[mae]
decoder_dim=2048