arch = "eegnet"
data_path = "/kreka/research/willy/side/brain_datasets/alljoined-isolated-epochs-2025-12-25/alljoined-isolated-epochs-2025-12-25-train.safetensors"
dataset = "sparse_classification"
class_col = "super_category_id"

epochs = 100

shuffle = false
weight_decay=0
lr=1e-3
batch_size=1024

[eegnet]
num_channels = 32
num_samples = 78
num_classes = 8
dropout_rate=0
