arch = "eegnet"
data_path = "/kreka/research/willy/side/brain_datasets/alljoined-isolated-epochs-2025-12-25/alljoined-isolated-epochs-2025-12-25-train.safetensors"
dataset = "sparse_classification"
class_col = "subject"

epochs = 10

[eegnet]
num_channels = 32
num_samples = 76
num_classes = 8
