data_path = "/kreka/research/willy/side/brain_datasets/alljoined-window-2025-12-14/alljoined-window-2025-12-14-train.safetensors"
dataset = "sparse"

[mae]
channels=32
masking_ratio=0.5
dim = 1024
depth = 6
heads = 16
dim_head = 64
mlp_dim = 4096